[project]
name = "rust-sentiment-anew"
version = "0.1.0"
description = "Reddit sentiment analysis using ANEW (posts + comments)."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["requests>=2.32.0"]

